// <auto-generated />
using System;
using Global.Delivery.Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Global.Delivery.Infraestructure.Migrations
{
    [DbContext(typeof(DeliveryManagementContext))]
    [Migration("20240824233913_update-datetime")]
    partial class updatedatetime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Global.Delivery.Domain.Entities.DeliverymanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DT_OF_BIRTH");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DOCUMENT");

                    b.Property<string>("LicenseImage")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("LICENSE_IMAGE");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("LICENSE_NUMBER");

                    b.Property<int>("LicenseType")
                        .HasColumnType("integer")
                        .HasColumnName("LICENSE_TYPE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("TB_DELIVERYMAN", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
